# -*- coding: utf-8 -*-
"""Assignmnet_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3pZnVRJ0HCcrWVUaxgdWIQu8vXfGY82
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

data = pd.read_csv('/content/data.txt')
df = pd.DataFrame(data)

df['sales'] = [100, 200, 150, 120, 180, 110, 250, 300, 220, 280, 200, 130, 160, 140, 260, 240, 210, 190, 170, 230, 290, 270, 250]

le = LabelEncoder()
df['prod_cat'] = le.fit_transform(df['prod_cat'])
df['prod_subcat'] = le.fit_transform(df['prod_subcat'])

X = df[['prod_cat_code', 'prod_cat', 'prod_sub_cat_code', 'prod_subcat']]
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')


print('Coefficients:')
print(model.coef_)

plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue')
plt.plot([y.min(), y.max()], [y.min(), y.max()], color='red', lw=2)
plt.xlabel('Actual Sales')
plt.ylabel('Predicted Sales')
plt.title('Actual vs Predicted Sales')

